# 로컬 개발용 설정

kdb:
  filepath: C:/epams/ # 첨부파일, 이미지 등 저장할 filesystem 경로
  logpath: C:/epams/ # 로그 파일 저장 경로
  logfile: ePAMS_logback.log

# server port
server:
  port: 8080
  servlet: 
    session:
      timeout: 15m
      persistent: true
      tracking-modes: cookie
      cookie:
        domain: localhost # 로컬 개발 환경
  error:
    whitelabel:
      enabled: false # Spring Boot 기본 에러 경로를 비활성화하고 사용자 정의 컨트롤러를 사용할 수 있도록 설정

# webauthn & passkey
authn:
  display: ePAMS
  hostname: ${server.servlet.session.cookie.domain} 
  origin: http://localhost:8080

# spring
spring:
  devtools.livereload.enabled: true  # 로컬 개발 환경에서 livereload 활성화
  
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: EHR
    password: ${DB_PASSWORD}  # 시스템 환경변수 kdb1234! 세팅
    hikari:
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 1800000
      maximum-pool-size: 10

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl      
    show-sql: false
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        "[format_sql]": true
        default_schema: OEHR