# 사용자 정의 설정
kdb:
  indexBrdCnt: 3 # index 페이지에서 노출할 게시물 수
  listBrdCnt: 3 # list 페이지에서 한 화면에 노출할 게시물 수
  maxPageBtn: 5 # 모든 페이지네이션에서 최대로 노출할 버튼 수 
  simpleAuthStr: 간편인증 # 로깅 시 인증방식 중 간편인증에 대한 문구

# actuator
management:
  endpoints:  
    web:
      exposure:
        include: "*"
        #include: health,info,metrics
        #include: prometheus

  endpoint:
    health:
      show-details: always

# spring
spring:
  profiles:
    active: prod # 기본 활성 프로파일을 local로 설정 (운영: prod)

  application:
    name: ePAMS

  servlet:
    multipart:
      maxFileSize: 512MB # 파일 하나의 최대 크기
      maxRequestSize: 512MB  # 한 번에 최대 업로드 가능 용량

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    
  session:
    jdbc:
      initialize-schema: always

  web:
    resources:
      static-locations: classpath:/templates

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml