# server port
server:
  port: 8088


# database
spring:
  devtools.livereload.enabled: false
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: whdgns0910!
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

