# server port
server:
  port: 8081

# spring
spring:
  devtools.livereload.enabled: true  

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: whdgns0910!

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl      
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        "[format_sql]": true
    
  session:
    jdbc:
      initialize-schema: always


# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

