# 개발 서버용 설정 (java -jar epams.jar --spring.profiles.active=dev)

kdb:
  filepath: C:/epams/ # 첨부파일, 이미지 등 저장할 filesystem 경로
  logpath: C:/epams/ # 로그 파일 저장 경로
  logfile: ePAMS_logback.log

# server port
server:
  port: 8080
  servlet:
    session:
      timeout: 15m
      persistent: true
      tracking-modes: cookie
      cookie:
        domain: localhost # 로컬 개발 환경
  error:
    whitelabel:
      enabled: false # Spring Boot 기본 에러 경로를 비활성화하고 사용자 정의 컨트롤러를 사용할 수 있도록 설정


# webauthn & passkey
authn:
  display: ePAMS
  hostname: ${server.servlet.session.cookie.domain}
  origin: http://localhost:8080

# spring
spring:
  devtools.livereload.enabled: true  # 로컬 개발 환경에서 livereload 활성화

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${DB_URL}
    username: EHR
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 60000 # 1분(커넥션 풀에서 커넥션을 가져오는데 최대 대기 시간)
      idle-timeout: 300000 # 5분(커넥션 풀에 유휴 커넥션이 유지되는 시간)
      max-lifetime: 1800000 # 30분(커넥션 풀에 유휴 커넥션이 유지되는 최대 시간)
      maximum-pool-size: 20 # 최대 커넥션 수
      minimum-idle: 5 # 최소 커넥션 수
  sql:
    init:
      mode: always
      data-locations: classpath:init.sql

  # 나중에 실제로 운영에 배포할 떄는 꼭 지울것
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        "[format_sql]": true
        default_schema: OEHR