# server port
server:
  port: 8080
  servlet: 
    session:
      timeout: 15m
      persistent: true
      tracking-modes: cookie
      cookie:
        domain: localhost
        #domain: epams.duckdns.org
        #http-only: true
        #path: /
        #max-age: -1 # infinite
        #secure: true # https only allowed
        #sameSite: strict

# actuator
management:
  endpoints:  
    web:
      exposure:
        include: prometheus

# spring
spring:
  servlet:
    multipart:
      maxFileSize: 512MB # 파일 하나의 최대 크기
      maxRequestSize: 512MB  # 한 번에 최대 업로드 가능 용량
          
  devtools.livereload.enabled: true  
  
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
    #url: jdbc:oracle:thin:@192.168.0.10:1521:ORCLCDB
#    url: jdbc:oracle:thin:@epams.duckdns.org:1521:ORCLCDB
#    username: ehr
#    password: kdb1234!
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ehr?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: whdgns0910!

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl      
    show-sql: false
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        "[format_sql]": true
    
  session:
    jdbc:
      initialize-schema: always
      
  web:
    resources:
      static-locations: classpath:/templates


# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

