# 운영 서버용 설정 (java -jar epams.jar --spring.profiles.active=prod)

kdb:
  filepath: /epams/ # 첨부파일, 이미지 등 저장할 filesystem 경로
  logpath: /epams/ # 로그 파일 저장 경로
  logfile: epams_logback.log

# server port
server:
  port: 8080
  servlet:
    session:
      timeout: 15m
      persistent: true
      tracking-modes: cookie
      cookie:
        domain: epams.duckdns.org
        http-only: true
        path: /
        max-age: -1 # infinite
        secure: true # https only allowed
        sameSite: strict

# webauthn & passkey
authn:
  display: ePAMS
  hostname: ${server.servlet.session.cookie.domain}
  origin: https://${server.servlet.session.cookie.domain}

# spring
spring:  
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.10:1521:ORCLCDB
    username: EHR
    password: ${DB_PASSWORD}  # 시스템 환경변수 kdb1234! 세팅

  # 나중에 실제로 운영에 배포할 떄는 꼭 지울것
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        "[format_sql]": true