# server port
server:
  port: 8080
  servlet: 
    session:
      timeout: 30m
      persistent: true
      tracking-modes: cookie
      cookie:
<<<<<<< HEAD
        domain: epams.duckdns.org
        #domain: epams.iptime.org
        #domain: localhost
=======
        #domain: epams.iptime.org
        domain: localhost
>>>>>>> 91410e5dd2d2c3e97e3184e2ec66e28bddf61a1f
        http-only: true
        path: /
        max-age: -1 # infinite
        #secure: true # https only allowed

# spring
spring:
  devtools.livereload.enabled: true  
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: whdgns0910!

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl      
    show-sql: false
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        "[format_sql]": true
    
  session:
    jdbc:
      initialize-schema: always
      
  web:
    resources:
      static-locations: classpath:/templates


# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

