CREATE TABLE "OHR"."DTM_HIS"
(
    "DTM_HIS_ID"      NUMBER       NOT NULL ENABLE,
    "EMP_ID"          NUMBER       NOT NULL ENABLE,
    "DTM_KIND_CD"     VARCHAR2(10) NOT NULL ENABLE,
    "DTM_REASON_CD"   VARCHAR2(10) NOT NULL ENABLE,
    "STA_YMD"         DATE         NOT NULL ENABLE,
    "STA_HM"          CHAR(4),
    "END_YMD"         DATE         NOT NULL ENABLE,
    "END_HM"          CHAR(4),
    "DTM_REASON"      VARCHAR2(256),
    "DEST_PLC"        VARCHAR2(300),
    "TELNO"           VARCHAR2(20),
    "CHILD_NO"        VARCHAR2(15),
    "APPL_ID"         NUMBER       NOT NULL ENABLE,
    "STAT_CD"         VARCHAR2(10) NOT NULL ENABLE,
    "FINAL_APPR_YMD"  DATE,
    "MODI_TYPE"       VARCHAR2(10),
    "MODI_REASON"     VARCHAR2(200),
    "MODI_DTM_HIS_ID" NUMBER,
    "MOD_USER_ID"     NUMBER       NOT NULL ENABLE,
    "MOD_DATE"        DATE         NOT NULL ENABLE,
    "TZ_CD"           VARCHAR2(10) NOT NULL ENABLE,
    "TZ_DATE"         DATE         NOT NULL ENABLE,
    "COMPANY_NM"      VARCHAR2(20),
    "DOCUMENT"        VARCHAR2(50),
    "AD_USE_YN"       VARCHAR2(10),
    "MAIL_SEND_YN"    VARCHAR2(10),
    "ESB_ASK_DT"      VARCHAR2(100),
    "CHILD_BIRTH_YMD" DATE,
    "DTM_STORE_YN"    VARCHAR2(10),
    "FILE_ID"         NUMBER,
    "SEAL_MGR_YN"     CHAR(1),
    "SECU_MGR_YN"     CHAR(1),
    "INFO_MGR_YN"     CHAR(1),
    "SAFE_MGR_YN"     CHAR(1),
    "PLACE_CD"        VARCHAR2(10),

    CONSTRAINT "PK_DTM_HIS" PRIMARY KEY ("DTM_HIS_ID")
);

CREATE SEQUENCE OHR.S_DTM_SEQUENCE INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER;

COMMENT ON TABLE OHR.DTM_HIS IS '근태내역';

COMMENT ON COLUMN OHR.DTM_HIS.DTM_HIS_ID IS '근태내역ID';

COMMENT ON COLUMN OHR.DTM_HIS.EMP_ID IS '직원ID';

COMMENT ON COLUMN OHR.DTM_HIS.DTM_KIND_CD IS '근태종류코드 [DTM_KIND_CD]';

COMMENT ON COLUMN OHR.DTM_HIS.DTM_REASON_CD IS '근태사유코드 [DTM_REASON_CD]';

COMMENT ON COLUMN OHR.DTM_HIS.STA_YMD IS '시작일';

COMMENT ON COLUMN OHR.DTM_HIS.STA_HM IS '시작시각';

COMMENT ON COLUMN OHR.DTM_HIS.END_YMD IS '종료일';

COMMENT ON COLUMN OHR.DTM_HIS.END_HM IS '종료시각';

COMMENT ON COLUMN OHR.DTM_HIS.DTM_REASON IS '근태사유';

COMMENT ON COLUMN OHR.DTM_HIS.DEST_PLC IS '행선지';

COMMENT ON COLUMN OHR.DTM_HIS.TELNO IS '연락처';

COMMENT ON COLUMN OHR.DTM_HIS.CHILD_NO IS '아이순번';

COMMENT ON COLUMN OHR.DTM_HIS.APPL_ID IS '신청서ID';

COMMENT ON COLUMN OHR.DTM_HIS.STAT_CD IS '신청서상태코드 [ELA_STAT_CD]';

COMMENT ON COLUMN OHR.DTM_HIS.FINAL_APPR_YMD IS '최종승인일';

COMMENT ON COLUMN OHR.DTM_HIS.MODI_TYPE IS '수정구분(UPDATE:변경,DELETE:취소)';

COMMENT ON COLUMN OHR.DTM_HIS.MODI_REASON IS '수정사유';

COMMENT ON COLUMN OHR.DTM_HIS.MODI_DTM_HIS_ID IS '수정근태내역ID';

COMMENT ON COLUMN OHR.DTM_HIS.MOD_USER_ID IS '변경자';

COMMENT ON COLUMN OHR.DTM_HIS.MOD_DATE IS '변경일시';

COMMENT ON COLUMN OHR.DTM_HIS.TZ_CD IS '타임존코드';

COMMENT ON COLUMN OHR.DTM_HIS.TZ_DATE IS '타임존일시';

COMMENT ON COLUMN OHR.DTM_HIS.AD_USE_YN IS '선연차사용여부';

COMMENT ON COLUMN OHR.DTM_HIS.MAIL_SEND_YN IS '메일발송여부';

COMMENT ON COLUMN OHR.DTM_HIS.ESB_ASK_DT IS 'ESB요청일시';

COMMENT ON COLUMN OHR.DTM_HIS.CHILD_BIRTH_YMD IS '자녀출생';

COMMENT ON COLUMN OHR.DTM_HIS.DTM_STORE_YN IS '연차저축여부';

COMMENT ON COLUMN OHR.DTM_HIS.FILE_ID IS '첨부파일ID';

COMMENT ON COLUMN OHR.DTM_HIS.SEAL_MGR_YN IS '인장담당자여부';

COMMENT ON COLUMN OHR.DTM_HIS.SECU_MGR_YN IS '보안담당자여부';

COMMENT ON COLUMN OHR.DTM_HIS.INFO_MGR_YN IS '정보취급관리자';

COMMENT ON COLUMN OHR.DTM_HIS.SAFE_MGR_YN IS '보안관리자';

COMMENT ON COLUMN OHR.DTM_HIS.PLACE_CD IS '스마트워크 장소코드[DTM_SMART_PLACE_CD]';


CREATE TABLE "OHR"."ELA_APPL_C"
(
    "APPL_ID"         NUMBER(22, 0)     NOT NULL ENABLE,
    "APPL_CD"         VARCHAR2(10)      NOT NULL ENABLE,
    "EMP_ID"          NUMBER(22, 0)     NOT NULL ENABLE,
    "APPL_DATE"       DATE              NOT NULL ENABLE,
    "MAKE_EMP_ID"     NUMBER(22, 0)     NOT NULL ENABLE,
    "STAT_CD"         VARCHAR2(10)      NOT NULL ENABLE,
    "FORCE_CANCEL_YN" CHAR(1) DEFAULT 0 NOT NULL ENABLE,
    "NOTE"            VARCHAR2(200),
    "MOD_USER_ID"     NUMBER(22, 0)     NOT NULL ENABLE,
    "MOD_DATE"        DATE              NOT NULL ENABLE,
    "TZ_CD"           VARCHAR2(10)      NOT NULL ENABLE,
    "TZ_DATE"         DATE              NOT NULL ENABLE,
    CONSTRAINT "PK_ELA_APPL_C" PRIMARY KEY ("APPL_ID")
);


CREATE SEQUENCE OHR.S_ELA_SEQUENCE INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER;

COMMENT ON TABLE OHR.ELA_APPL_C IS '신청서';

COMMENT ON COLUMN OHR.ELA_APPL_C.APPL_ID IS '신청서ID';

COMMENT ON COLUMN OHR.ELA_APPL_C.APPL_CD IS '신청서종류코드';

COMMENT ON COLUMN OHR.ELA_APPL_C.EMP_ID IS '직원ID';

COMMENT ON COLUMN OHR.ELA_APPL_C.APPL_DATE IS '승인신청일시';

COMMENT ON COLUMN OHR.ELA_APPL_C.MAKE_EMP_ID IS '작성자ID';

COMMENT ON COLUMN OHR.ELA_APPL_C.STAT_CD IS '신청서상태코드';

COMMENT ON COLUMN OHR.ELA_APPL_C.FORCE_CANCEL_YN IS '강제반려여부';

COMMENT ON COLUMN OHR.ELA_APPL_C.NOTE IS '비고';

COMMENT ON COLUMN OHR.ELA_APPL_C.MOD_USER_ID IS '변경자';

COMMENT ON COLUMN OHR.ELA_APPL_C.MOD_DATE IS '변경일시';

COMMENT ON COLUMN OHR.ELA_APPL_C.TZ_CD IS '타임존코드';

COMMENT ON COLUMN OHR.ELA_APPL_C.TZ_DATE IS '타임존일시';


-- OHR.ELA_APPL_TR_C definition


CREATE TABLE "OHR"."ELA_APPL_TR_C"
(
    "APPR_KIND"         CHAR(1)       NOT NULL ENABLE,
    "APPL_ID"           NUMBER(22, 0) NOT NULL ENABLE,
    "ORD_NO"            NUMBER(2, 0)  NOT NULL ENABLE,
    "APPR_EMP_ID"       NUMBER(22, 0),
    "APPR_USERGROUP_ID" VARCHAR2(100),
    "APPR_CD"           VARCHAR2(10),
    "APPR_DATE"         DATE,
    "APPR_INFO"         VARCHAR2(200),
    "REFUSAL_REASON"    VARCHAR2(200),
    "NOTE"              VARCHAR2(200),
    "MOD_USER_ID"       NUMBER(22, 0) NOT NULL ENABLE,
    "MOD_DATE"          DATE          NOT NULL ENABLE,
    "TZ_CD"             VARCHAR2(10)  NOT NULL ENABLE,
    "TZ_DATE"           DATE          NOT NULL ENABLE,
    CONSTRAINT "PK_ELA_APPL_TR_C" PRIMARY KEY ("APPL_ID", "APPR_KIND", "ORD_NO")
);



COMMENT ON TABLE OHR.ELA_APPL_TR_C IS '신청서결재내역';

COMMENT ON COLUMN OHR.ELA_APPL_TR_C.APPR_KIND IS '요청승인구분';

COMMENT ON COLUMN OHR.ELA_APPL_TR_C.APPL_ID IS '신청서ID';

COMMENT ON COLUMN OHR.ELA_APPL_TR_C.ORD_NO IS '결재순번';

COMMENT ON COLUMN OHR.ELA_APPL_TR_C.APPR_EMP_ID IS '결재직원ID';

COMMENT ON COLUMN OHR.ELA_APPL_TR_C.APPR_USERGROUP_ID IS '결재자역할ID';

COMMENT ON COLUMN OHR.ELA_APPL_TR_C.APPR_CD IS '결재코드';

COMMENT ON COLUMN OHR.ELA_APPL_TR_C.APPR_DATE IS '결재일시';

COMMENT ON COLUMN OHR.ELA_APPL_TR_C.APPR_INFO IS '결재자정보';

COMMENT ON COLUMN OHR.ELA_APPL_TR_C.REFUSAL_REASON IS '반려사유';

COMMENT ON COLUMN OHR.ELA_APPL_TR_C.NOTE IS '비고';

COMMENT ON COLUMN OHR.ELA_APPL_TR_C.MOD_USER_ID IS '변경자';

COMMENT ON COLUMN OHR.ELA_APPL_TR_C.MOD_DATE IS '변경일시';

COMMENT ON COLUMN OHR.ELA_APPL_TR_C.TZ_CD IS '타임존코드';

COMMENT ON COLUMN OHR.ELA_APPL_TR_C.TZ_DATE IS '타임존일시';


-- OHR.IF_IAM_USER definition
CREATE TABLE "OHR"."IF_IAM_USER"
(
    "EMP_NO"  VARCHAR2(20)  NOT NULL ENABLE,
    "EMP_NM"  VARCHAR2(200) NOT NULL ENABLE,
    "EMP_PWD" VARCHAR2(256) NOT NULL ENABLE,
    "TZ_DATE" DATE          NOT NULL ENABLE,
    CONSTRAINT "PK_IF_IAM_USER" PRIMARY KEY ("EMP_NO")
);



COMMENT ON TABLE OHR.IF_IAM_USER IS 'IAM_사용자';

COMMENT ON COLUMN OHR.IF_IAM_USER.EMP_NO IS '행번';

COMMENT ON COLUMN OHR.IF_IAM_USER.EMP_NM IS '성명';

COMMENT ON COLUMN OHR.IF_IAM_USER.EMP_PWD IS '비밀번호';

COMMENT ON COLUMN OHR.IF_IAM_USER.TZ_DATE IS '타임존 일시';


-- OHR.XFRMD2C definition (공통코드)
CREATE TABLE OHR.XFRMD2C
(
    CD_ID       NUMBER(22) NOT NULL,
    CD          VARCHAR2(10) NOT NULL,
    CD_NM       VARCHAR2(200),
    SYSTEM_CD   VARCHAR2(10),
    SHORT_NM    VARCHAR2(100),
    LOCALE_CD   VARCHAR2(10) DEFAULT null NOT NULL,
    COMPANY_CD  VARCHAR2(10) NOT NULL,
    CD_KIND     VARCHAR2(200) NOT NULL,
    STA_YMD     DATE NOT NULL,
    END_YMD     DATE NOT NULL,
    FOR_NM      VARCHAR2(200),
    FOR_FULL_NM VARCHAR2(200),
    PRINT_NM    VARCHAR2(200),
    ORD_NO      VARCHAR2(10),
    CONV_CD     VARCHAR2(40),
    ETC_CD1     VARCHAR2(200),
    ETC_CD2     VARCHAR2(200),
    ETC_CD3     VARCHAR2(200),
    ETC_CD4     VARCHAR2(200),
    ETC_CD5     VARCHAR2(200),
    ETC_CD6     VARCHAR2(200),
    ETC_CD7     VARCHAR2(200),
    ETC_CD8     VARCHAR2(200),
    ETC_CD9     VARCHAR2(200),
    ETC_CD10    VARCHAR2(200),
    NOTE        VARCHAR2(200),
    MOD_USER_ID NUMBER(22) NOT NULL,
    MOD_DATE    DATE NOT NULL,
    TZ_CD       VARCHAR2(10) DEFAULT null NOT NULL,
    TZ_DATE     DATE DEFAULT null NOT NULL,
    ETC_CD11    VARCHAR2(200)
);

ALTER TABLE OHR.XFRMD2C
    ADD CONSTRAINT PK_XFRMD2C PRIMARY KEY (CD_ID);

COMMENT ON TABLE OHR.XFRMD2C IS '공통코드';
COMMENT ON COLUMN OHR.XFRMD2C.CD_ID IS '코드id';
COMMENT ON COLUMN OHR.XFRMD2C.CD IS '코드';
COMMENT ON COLUMN OHR.XFRMD2C.CD_NM IS '코드명';
COMMENT ON COLUMN OHR.XFRMD2C.SYSTEM_CD IS '시스템코드';
COMMENT ON COLUMN OHR.XFRMD2C.SHORT_NM IS '코드약명';
COMMENT ON COLUMN OHR.XFRMD2C.LOCALE_CD IS '다국어지역코드';
COMMENT ON COLUMN OHR.XFRMD2C.COMPANY_CD IS '인사영역코드';
COMMENT ON COLUMN OHR.XFRMD2C.CD_KIND IS '코드분류';
COMMENT ON COLUMN OHR.XFRMD2C.STA_YMD IS '시작일자';
COMMENT ON COLUMN OHR.XFRMD2C.END_YMD IS '종료일자';
COMMENT ON COLUMN OHR.XFRMD2C.FOR_NM IS '외국어명';
COMMENT ON COLUMN OHR.XFRMD2C.FOR_FULL_NM IS '외국어Full명';
COMMENT ON COLUMN OHR.XFRMD2C.PRINT_NM IS '출력명';
COMMENT ON COLUMN OHR.XFRMD2C.ORD_NO IS '정렬순서';
COMMENT ON COLUMN OHR.XFRMD2C.CONV_CD IS '변환코드';
COMMENT ON COLUMN OHR.XFRMD2C.ETC_CD1 IS '기타코드1';
COMMENT ON COLUMN OHR.XFRMD2C.ETC_CD2 IS '기타코드2';
COMMENT ON COLUMN OHR.XFRMD2C.ETC_CD3 IS '기타코드3';
COMMENT ON COLUMN OHR.XFRMD2C.ETC_CD4 IS '기타코드4';
COMMENT ON COLUMN OHR.XFRMD2C.ETC_CD5 IS '기타코드5';
COMMENT ON COLUMN OHR.XFRMD2C.ETC_CD6 IS '기타코드6';
COMMENT ON COLUMN OHR.XFRMD2C.ETC_CD7 IS '기타코드7';
COMMENT ON COLUMN OHR.XFRMD2C.ETC_CD8 IS '기타코드8';
COMMENT ON COLUMN OHR.XFRMD2C.ETC_CD9 IS '기타코드9';
COMMENT ON COLUMN OHR.XFRMD2C.ETC_CD10 IS '기타코드10';
COMMENT ON COLUMN OHR.XFRMD2C.NOTE IS '비고';
COMMENT ON COLUMN OHR.XFRMD2C.MOD_USER_ID IS '변경자';
COMMENT ON COLUMN OHR.XFRMD2C.MOD_DATE IS '변경일시';
COMMENT ON COLUMN OHR.XFRMD2C.TZ_CD IS '타임존코드';
COMMENT ON COLUMN OHR.XFRMD2C.TZ_DATE IS '타임존일시';