CREATE TABLE HURCO_SESSM (
    SESSION_ID VARCHAR2(36) NOT NULL PRIMARY KEY,
    CREATION_TIME TIMESTAMP NOT NULL,
    LAST_ACCESS_TIME TIMESTAMP NOT NULL,
    MAX_INACTIVE_INTERVAL NUMBER NOT NULL,
    EXPIRY_TIME TIMESTAMP NOT NULL,
    PRINCIPAL_NAME VARCHAR2(100),
    SESSION_ATTRIBUTES BLOB
);

CREATE INDEX CUSTOM_SESSION_IDX ON HURCO_SESSM(EXPIRY_TIME);


CREATE TABLE HURCO_SESSD (
    SESSION_PRIMARY_ID VARCHAR2(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR2(200) NOT NULL,
    ATTRIBUTE_BYTES BLOB NOT NULL,
    PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES HURCO_SESSM (SESSION_ID) ON DELETE CASCADE
);