CREATE TABLE EHR.THURXE_CSSESM (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME NUMBER NOT NULL,
    LAST_ACCESS_TIME NUMBER NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME NUMBER NOT NULL,
    PRINCIPAL_NAME VARCHAR2(100),
    CONSTRAINT THURXE_CSSESM_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX THURXE_CSSESM_IX1 ON EHR.THURXE_CSSESM (SESSION_ID);
CREATE INDEX THURXE_CSSESM_IX2 ON EHR.THURXE_CSSESM (EXPIRY_TIME);
CREATE INDEX THURXE_CSSESM_IX3 ON EHR.THURXE_CSSESM (PRINCIPAL_NAME);

COMMENT ON TABLE EHR.THURXE_CSSESM IS '인사_외부근태 세션정보테이블';
COMMENT ON COLUMN EHR.THURXE_CSSESM.PRIMARY_ID IS '기본 ID';
COMMENT ON COLUMN EHR.THURXE_CSSESM.SESSION_ID IS '세션 ID';
COMMENT ON COLUMN EHR.THURXE_CSSESM.CREATION_TIME IS '세션 생성 시간';
COMMENT ON COLUMN EHR.THURXE_CSSESM.LAST_ACCESS_TIME IS '마지막 접근 시간';
COMMENT ON COLUMN EHR.THURXE_CSSESM.MAX_INACTIVE_INTERVAL IS '최대 비활성화 간격';
COMMENT ON COLUMN EHR.THURXE_CSSESM.EXPIRY_TIME IS '세션 만료 시간';
COMMENT ON COLUMN EHR.THURXE_CSSESM.PRINCIPAL_NAME IS '주체 이름';

CREATE TABLE EHR.THURXE_CSSESD (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR2(200) NOT NULL,
    ATTRIBUTE_BYTES BLOB NOT NULL,
    CONSTRAINT THURXE_CSSESD_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT THURXE_CSSESD_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES EHR.THURXE_CSSESM(PRIMARY_ID) ON DELETE CASCADE
);

COMMENT ON TABLE EHR.THURXE_CSSESD IS '인사_외부근태 세션속성테이블';
COMMENT ON COLUMN EHR.THURXE_CSSESD.SESSION_PRIMARY_ID IS '세션 기본 ID';
COMMENT ON COLUMN EHR.THURXE_CSSESD.ATTRIBUTE_NAME IS '속성 이름';
COMMENT ON COLUMN EHR.THURXE_CSSESD.ATTRIBUTE_BYTES IS '속성 데이터';
