CREATE TABLE OEHR.THURXE_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME NUMBER NOT NULL,
    LAST_ACCESS_TIME NUMBER NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME NUMBER NOT NULL,
    PRINCIPAL_NAME VARCHAR2(100),
    CONSTRAINT THURXE_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX OEHR.THURXE_SESSION_IX1 ON OEHR.THURXE_SESSION (SESSION_ID);
CREATE INDEX OEHR.THURXE_SESSION_IX2 ON OEHR.THURXE_SESSION (EXPIRY_TIME);
CREATE INDEX OEHR.THURXE_SESSION_IX3 ON OEHR.THURXE_SESSION (PRINCIPAL_NAME);

COMMENT ON TABLE OEHR.THURXE_SESSION IS '인사_외부근태 세션정보테이블';
COMMENT ON COLUMN OEHR.THURXE_SESSION.PRIMARY_ID IS '기본 ID';
COMMENT ON COLUMN OEHR.THURXE_SESSION.SESSION_ID IS '세션 ID';
COMMENT ON COLUMN OEHR.THURXE_SESSION.CREATION_TIME IS '세션 생성 시간';
COMMENT ON COLUMN OEHR.THURXE_SESSION.LAST_ACCESS_TIME IS '마지막 접근 시간';
COMMENT ON COLUMN OEHR.THURXE_SESSION.MAX_INACTIVE_INTERVAL IS '최대 비활성화 간격';
COMMENT ON COLUMN OEHR.THURXE_SESSION.EXPIRY_TIME IS '세션 만료 시간';
COMMENT ON COLUMN OEHR.THURXE_SESSION.PRINCIPAL_NAME IS '주체 이름';

CREATE TABLE OEHR.THURXE_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR2(200) NOT NULL,
    ATTRIBUTE_BYTES BLOB NOT NULL,
    CONSTRAINT THURXE_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT THURXE_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES OEHR.THURXE_SESSION(PRIMARY_ID) ON DELETE CASCADE
);

COMMENT ON TABLE OEHR.THURXE_SESSION_ATTRIBUTES IS '인사_외부근태 세션속성테이블';
COMMENT ON COLUMN OEHR.THURXE_SESSION_ATTRIBUTES.SESSION_PRIMARY_ID IS '세션 기본 ID';
COMMENT ON COLUMN OEHR.THURXE_SESSION_ATTRIBUTES.ATTRIBUTE_NAME IS '속성 이름';
COMMENT ON COLUMN OEHR.THURXE_SESSION_ATTRIBUTES.ATTRIBUTE_BYTES IS '속성 데이터';