-- 사용자 계정 생성 시 제약조건 삭제
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- 사용자 계정 및 스키마 생성
create user OEHR identified by "kdb1234!";

-- 테이블 스페이스 할당
ALTER USER OEHR DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

-- 기본 권한 부여
GRANT SELECT ANY TABLE, CREATE SESSION, CREATE TABLE, CREATE VIEW to OEHR;
GRANT CREATE ANY TABLE to OEHR;
GRANT RESOURCE TO OEHR;
GRANT CONNECT TO OEHR;

-- 테이블 스페이스 할당
ALTER USER OEHR DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

-- 시퀀스 생성

CREATE SEQUENCE OEHR.SQ_THURXE_CBRDFM_1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE OEHR.SQ_THURXE_CBRDIM_1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE OEHR.SQ_THURXE_CBRDMM_1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE OEHR.SQ_THURXE_CWCRDM_1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE OEHR.SQ_THURXE_CLOGNL_1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE OEHR.SQ_THURXE_COTPIM_1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;
CREATE SEQUENCE OEHR.SQ_THURXE_CVIEWL_1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

-- 테이블 생성

CREATE TABLE OEHR.THURXE_CATHLI (
                                    ATH_ID VARCHAR2(32),
                                    DEL_YN VARCHAR2(1),
                                    FST_ENR_DTM DATE,
                                    FST_ENR_USID VARCHAR2(14),
                                    GUID VARCHAR2(38),
                                    GUID_PRG_SNO NUMBER(4,0),
                                    LST_CHG_DTM DATE,
                                    LST_CHG_USID VARCHAR2(14),
                                    QLF_GR_MAT VARCHAR2(600),
                                    QLF_GR_NM VARCHAR2(200),
                                    USE_YN VARCHAR2(1),
                                    CONSTRAINT SYS_C0011066 CHECK ("ATH_ID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011067 CHECK ("DEL_YN" IS NOT NULL),
                                    CONSTRAINT SYS_C0011068 CHECK ("FST_ENR_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011069 CHECK ("GUID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011070 CHECK ("GUID_PRG_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011071 CHECK ("LST_CHG_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011072 PRIMARY KEY (ATH_ID)
);


-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE OEHR.THURXE_CBRDMM;

CREATE TABLE OEHR.THURXE_CBRDMM (
                                    BLB_SNO NUMBER(22,0),
                                    DEL_YN VARCHAR2(1),
                                    FST_ENR_DTM DATE,
                                    FST_ENR_USID VARCHAR2(14),
                                    GUID VARCHAR2(38),
                                    GUID_PRG_SNO NUMBER(4,0),
                                    LST_CHG_DTM DATE,
                                    LST_CHG_USID VARCHAR2(14),
                                    BLB_CONE VARCHAR2(4000),
                                    BLB_NM VARCHAR2(300),
                                    CTG_NM VARCHAR2(60),
                                    DUPR_ENO VARCHAR2(32),
                                    FL_APG_YN VARCHAR2(1),
                                    NAC_INQ_NBR NUMBER(10,0),
                                    CONSTRAINT SYS_C0011089 CHECK ("BLB_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011090 CHECK ("DEL_YN" IS NOT NULL),
                                    CONSTRAINT SYS_C0011091 CHECK ("FST_ENR_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011092 CHECK ("GUID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011093 CHECK ("GUID_PRG_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011094 CHECK ("LST_CHG_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011095 CHECK ("BLB_CONE" IS NOT NULL),
                                    CONSTRAINT SYS_C0011096 CHECK ("BLB_NM" IS NOT NULL),
                                    CONSTRAINT SYS_C0011097 CHECK ("CTG_NM" IS NOT NULL),
                                    CONSTRAINT SYS_C0011098 CHECK ("DUPR_ENO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011099 PRIMARY KEY (BLB_SNO)
);

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE OEHR.THURXE_CBRDFM;

CREATE TABLE OEHR.THURXE_CBRDFM (
                                    BLB_APG_FL_SNO NUMBER(22,0),
                                    DEL_YN VARCHAR2(1),
                                    FST_ENR_DTM DATE,
                                    FST_ENR_USID VARCHAR2(14),
                                    GUID VARCHAR2(38),
                                    GUID_PRG_SNO NUMBER(4,0),
                                    LST_CHG_DTM DATE,
                                    LST_CHG_USID VARCHAR2(14),
                                    FL_KPN_PTH VARCHAR2(255),
                                    ORC_FL_NM VARCHAR2(255),
                                    SVR_FL_NM VARCHAR2(255),
                                    BLB_SNO NUMBER(22,0),
                                    CONSTRAINT SYS_C0011073 CHECK ("BLB_APG_FL_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011074 CHECK ("DEL_YN" IS NOT NULL),
                                    CONSTRAINT SYS_C0011075 CHECK ("FST_ENR_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011076 CHECK ("GUID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011077 CHECK ("GUID_PRG_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011078 CHECK ("LST_CHG_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011079 PRIMARY KEY (BLB_APG_FL_SNO),
                                    CONSTRAINT FK_THURXE_CBRDFM_BLB_SNO FOREIGN KEY (BLB_SNO) REFERENCES OEHR.THURXE_CBRDMM(BLB_SNO) ON DELETE CASCADE
);

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE OEHR.THURXE_CBRDIM;

CREATE TABLE OEHR.THURXE_CBRDIM (
                                    BLB_IMG_SNO NUMBER(22,0),
                                    DEL_YN VARCHAR2(1),
                                    FST_ENR_DTM DATE,
                                    FST_ENR_USID VARCHAR2(14),
                                    GUID VARCHAR2(38),
                                    GUID_PRG_SNO NUMBER(4,0),
                                    LST_CHG_DTM DATE,
                                    LST_CHG_USID VARCHAR2(14),
                                    ORC_FL_NM VARCHAR2(255),
                                    SVR_FL_NM VARCHAR2(100),
                                    BLB_SNO NUMBER(22,0),
                                    CONSTRAINT SYS_C0011080 CHECK ("BLB_IMG_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011081 CHECK ("DEL_YN" IS NOT NULL),
                                    CONSTRAINT SYS_C0011082 CHECK ("FST_ENR_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011083 CHECK ("GUID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011084 CHECK ("GUID_PRG_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011085 CHECK ("LST_CHG_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011086 CHECK ("ORC_FL_NM" IS NOT NULL),
                                    CONSTRAINT SYS_C0011087 CHECK ("SVR_FL_NM" IS NOT NULL),
                                    CONSTRAINT SYS_C0011088 PRIMARY KEY (BLB_IMG_SNO),
                                    CONSTRAINT FK_THURXE_CBRDIM_BLB_SNO FOREIGN KEY (BLB_SNO) REFERENCES OEHR.THURXE_CBRDMM(BLB_SNO) ON DELETE CASCADE
);

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE OEHR.THURXE_CCDHTA;

CREATE TABLE OEHR.THURXE_CCDHTA (
                                    DEL_YN VARCHAR2(1),
                                    FST_ENR_DTM DATE,
                                    FST_ENR_USID VARCHAR2(14),
                                    GUID VARCHAR2(38),
                                    GUID_PRG_SNO NUMBER(4,0),
                                    LST_CHG_DTM DATE,
                                    LST_CHG_USID VARCHAR2(14),
                                    SRE_VCB_CDVA_ID VARCHAR2(40),
                                    HTML_FL_PTH VARCHAR2(2000),
                                    CONSTRAINT SYS_C0011100 CHECK ("DEL_YN" IS NOT NULL),
                                    CONSTRAINT SYS_C0011101 CHECK ("FST_ENR_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011102 CHECK ("GUID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011103 CHECK ("GUID_PRG_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011104 CHECK ("LST_CHG_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011105 CHECK ("SRE_VCB_CDVA_ID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011106 CHECK ("HTML_FL_PTH" IS NOT NULL),
                                    CONSTRAINT SYS_C0011107 PRIMARY KEY (HTML_FL_PTH,SRE_VCB_CDVA_ID)
);

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE OEHR.THURXE_CHTMLM;

CREATE TABLE OEHR.THURXE_CHTMLM (
                                    HTML_FL_PTH VARCHAR2(2000),
                                    DEL_YN VARCHAR2(1),
                                    FST_ENR_DTM DATE,
                                    FST_ENR_USID VARCHAR2(14),
                                    GUID VARCHAR2(38),
                                    GUID_PRG_SNO NUMBER(4,0),
                                    LST_CHG_DTM DATE,
                                    LST_CHG_USID VARCHAR2(14),
                                    HTML_FL_NM VARCHAR2(100),
                                    CONSTRAINT SYS_C0011108 CHECK ("HTML_FL_PTH" IS NOT NULL),
                                    CONSTRAINT SYS_C0011109 CHECK ("DEL_YN" IS NOT NULL),
                                    CONSTRAINT SYS_C0011110 CHECK ("FST_ENR_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011111 CHECK ("GUID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011112 CHECK ("GUID_PRG_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011113 CHECK ("LST_CHG_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011114 CHECK ("HTML_FL_NM" IS NOT NULL),
                                    CONSTRAINT SYS_C0011115 PRIMARY KEY (HTML_FL_PTH)
);

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE OEHR.THURXE_CCODEM;

CREATE TABLE OEHR.THURXE_CCODEM (
                                    SRE_VCB_CDVA_ID VARCHAR2(40),
                                    DEL_YN VARCHAR2(1),
                                    FST_ENR_DTM DATE,
                                    FST_ENR_USID VARCHAR2(14),
                                    GUID VARCHAR2(38),
                                    GUID_PRG_SNO NUMBER(4,0),
                                    LST_CHG_DTM DATE,
                                    LST_CHG_USID VARCHAR2(14),
                                    SRE_VCB_KD_NM VARCHAR2(200),
                                    SRE_VCB_NM VARCHAR2(200),
                                    CONSTRAINT SYS_C0011116 CHECK ("SRE_VCB_CDVA_ID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011117 CHECK ("DEL_YN" IS NOT NULL),
                                    CONSTRAINT SYS_C0011118 CHECK ("FST_ENR_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011119 CHECK ("GUID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011120 CHECK ("GUID_PRG_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011121 CHECK ("LST_CHG_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011122 CHECK ("SRE_VCB_KD_NM" IS NOT NULL),
                                    CONSTRAINT SYS_C0011123 CHECK ("SRE_VCB_NM" IS NOT NULL),
                                    CONSTRAINT SYS_C0011124 PRIMARY KEY (SRE_VCB_CDVA_ID)
);

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE OEHR.THURXE_CLOGNL;

CREATE TABLE OEHR.THURXE_CLOGNL (
                                    LGN_LOG_SNO NUMBER(22,0),
                                    DEL_YN VARCHAR2(1),
                                    FST_ENR_DTM DATE,
                                    FST_ENR_USID VARCHAR2(14),
                                    GUID VARCHAR2(38),
                                    GUID_PRG_SNO NUMBER(4,0),
                                    LST_CHG_DTM DATE,
                                    LST_CHG_USID VARCHAR2(14),
                                    CER_KD_NM VARCHAR2(100),
                                    ENO VARCHAR2(32),
                                    LGN_SCS_YN VARCHAR2(1),
                                    CONSTRAINT SYS_C0011125 CHECK ("LGN_LOG_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011126 CHECK ("DEL_YN" IS NOT NULL),
                                    CONSTRAINT SYS_C0011127 CHECK ("FST_ENR_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011128 CHECK ("GUID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011129 CHECK ("GUID_PRG_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011130 CHECK ("LST_CHG_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011131 CHECK ("CER_KD_NM" IS NOT NULL),
                                    CONSTRAINT SYS_C0011132 CHECK ("ENO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011133 CHECK ("LGN_SCS_YN" IS NOT NULL),
                                    CONSTRAINT SYS_C0011134 PRIMARY KEY (LGN_LOG_SNO)
);
-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE OEHR.THURXE_CORGLI;

CREATE TABLE OEHR.THURXE_CORGLI (
                                    PRLM_OGZ_C_CONE VARCHAR2(100),
                                    DEL_YN VARCHAR2(1),
                                    FST_ENR_DTM DATE,
                                    FST_ENR_USID VARCHAR2(14),
                                    GUID VARCHAR2(38),
                                    GUID_PRG_SNO NUMBER(4,0),
                                    LST_CHG_DTM DATE,
                                    LST_CHG_USID VARCHAR2(14),
                                    BBR_NM VARCHAR2(100),
                                    BBR_WREN_NM VARCHAR2(100),
                                    ITM_SQN_SNO VARCHAR2(9),
                                    PRLM_HRK_OGZ_C_CONE VARCHAR2(100),
                                    USE_YN VARCHAR2(1),
                                    CONSTRAINT SYS_C0011135 CHECK ("PRLM_OGZ_C_CONE" IS NOT NULL),
                                    CONSTRAINT SYS_C0011136 CHECK ("DEL_YN" IS NOT NULL),
                                    CONSTRAINT SYS_C0011137 CHECK ("FST_ENR_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011138 CHECK ("GUID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011139 CHECK ("GUID_PRG_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011140 CHECK ("LST_CHG_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011141 PRIMARY KEY (PRLM_OGZ_C_CONE)
);
-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE OEHR.THURXE_COTPIM;

CREATE TABLE OEHR.THURXE_COTPIM (
                                    OTP_ISN_SNO NUMBER(22,0),
                                    DEL_YN VARCHAR2(1),
                                    FST_ENR_DTM DATE,
                                    FST_ENR_USID VARCHAR2(14),
                                    GUID VARCHAR2(38),
                                    GUID_PRG_SNO NUMBER(4,0),
                                    LST_CHG_DTM DATE,
                                    LST_CHG_USID VARCHAR2(14),
                                    CER_KD_NM VARCHAR2(100),
                                    ENO VARCHAR2(32),
                                    OTP_SMS_CER_NO VARCHAR2(8),
                                    CONSTRAINT SYS_C0011142 CHECK ("OTP_ISN_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011143 CHECK ("DEL_YN" IS NOT NULL),
                                    CONSTRAINT SYS_C0011144 CHECK ("FST_ENR_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011145 CHECK ("GUID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011146 CHECK ("GUID_PRG_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011147 CHECK ("LST_CHG_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011148 CHECK ("ENO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011149 PRIMARY KEY (OTP_ISN_SNO)
);

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE OEHR.THURXE_CROLEM;

CREATE TABLE OEHR.THURXE_CROLEM (
                                    ENO VARCHAR2(32),
                                    DEL_YN VARCHAR2(1),
                                    FST_ENR_DTM DATE,
                                    FST_ENR_USID VARCHAR2(14),
                                    GUID VARCHAR2(38),
                                    GUID_PRG_SNO NUMBER(4,0),
                                    LST_CHG_DTM DATE,
                                    LST_CHG_USID VARCHAR2(14),
                                    ATH_ID VARCHAR2(32),
                                    CONSTRAINT SYS_C0011150 CHECK ("ENO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011151 CHECK ("DEL_YN" IS NOT NULL),
                                    CONSTRAINT SYS_C0011152 CHECK ("FST_ENR_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011153 CHECK ("GUID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011154 CHECK ("GUID_PRG_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011155 CHECK ("LST_CHG_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011156 CHECK ("ATH_ID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011157 PRIMARY KEY (ENO)
);

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE OEHR.THURXE_CUSATI;

CREATE TABLE OEHR.THURXE_CUSATI (
                                    ENO VARCHAR2(32),
                                    ATH_ID VARCHAR2(32),
                                    DEL_YN VARCHAR2(1),
                                    FST_ENR_DTM DATE,
                                    FST_ENR_USID VARCHAR2(14),
                                    GUID VARCHAR2(38),
                                    GUID_PRG_SNO NUMBER(4,0),
                                    LST_CHG_DTM DATE,
                                    LST_CHG_USID VARCHAR2(14),
                                    USE_YN VARCHAR2(1),
                                    CONSTRAINT SYS_C0011158 CHECK ("ENO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011159 CHECK ("ATH_ID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011160 CHECK ("DEL_YN" IS NOT NULL),
                                    CONSTRAINT SYS_C0011161 CHECK ("FST_ENR_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011162 CHECK ("GUID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011163 CHECK ("GUID_PRG_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011164 CHECK ("LST_CHG_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011165 PRIMARY KEY (ATH_ID,ENO)
);

-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE OEHR.THURXE_CUSRLI;

CREATE TABLE OEHR.THURXE_CUSRLI (
                                    ENO VARCHAR2(32),
                                    DEL_YN VARCHAR2(1),
                                    FST_ENR_DTM DATE,
                                    FST_ENR_USID VARCHAR2(14),
                                    USR_ECY_PWD VARCHAR2(100),
                                    GUID VARCHAR2(38),
                                    GUID_PRG_SNO NUMBER(4,0),
                                    LST_CHG_DTM DATE,
                                    LST_CHG_USID VARCHAR2(14),
                                    BBR_C VARCHAR2(3),
                                    CADR_TPN VARCHAR2(20),
                                    DTC_BBR_C VARCHAR2(3),
                                    DTS_DTL_CONE VARCHAR2(2000),
                                    ETR_MIL_ADDR_NM VARCHAR2(200),
                                    INLE_NO VARCHAR2(20),
                                    PT_C VARCHAR2(5),
                                    PT_C_NM VARCHAR2(200),
                                    TEM_C VARCHAR2(5),
                                    TEM_NM VARCHAR2(100),
                                    USE_YN VARCHAR2(1),
                                    USR_NM VARCHAR2(100),
                                    USR_WREN_NM VARCHAR2(100),
                                    CONSTRAINT SYS_C0011166 CHECK ("ENO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011167 CHECK ("DEL_YN" IS NOT NULL),
                                    CONSTRAINT SYS_C0011168 CHECK ("FST_ENR_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011169 CHECK ("GUID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011170 CHECK ("GUID_PRG_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011171 CHECK ("LST_CHG_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011172 PRIMARY KEY (ENO)
);
-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE OEHR.THURXE_CVIEWL;

CREATE TABLE OEHR.THURXE_CVIEWL (
                                    PAG_LOG_SNO NUMBER(22,0),
                                    DEL_YN VARCHAR2(1),
                                    FST_ENR_DTM DATE,
                                    FST_ENR_USID VARCHAR2(14),
                                    GUID VARCHAR2(38),
                                    GUID_PRG_SNO NUMBER(4,0),
                                    LST_CHG_DTM DATE,
                                    LST_CHG_USID VARCHAR2(14),
                                    CLI_IP_ADDR VARCHAR2(300),
                                    CTRL_NM VARCHAR2(500),
                                    MTH_NM VARCHAR2(100),
                                    REQ_URL_ADDR VARCHAR2(500),
                                    USR_CNC_ENV_CONE VARCHAR2(2000),
                                    CONSTRAINT SYS_C0011173 CHECK ("PAG_LOG_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011174 CHECK ("DEL_YN" IS NOT NULL),
                                    CONSTRAINT SYS_C0011175 CHECK ("FST_ENR_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011176 CHECK ("GUID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011177 CHECK ("GUID_PRG_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011178 CHECK ("LST_CHG_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011179 CHECK ("CLI_IP_ADDR" IS NOT NULL),
                                    CONSTRAINT SYS_C0011180 CHECK ("CTRL_NM" IS NOT NULL),
                                    CONSTRAINT SYS_C0011181 CHECK ("MTH_NM" IS NOT NULL),
                                    CONSTRAINT SYS_C0011182 CHECK ("REQ_URL_ADDR" IS NOT NULL),
                                    CONSTRAINT SYS_C0011183 CHECK ("USR_CNC_ENV_CONE" IS NOT NULL),
                                    CONSTRAINT SYS_C0011184 PRIMARY KEY (PAG_LOG_SNO)
);


-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE OEHR.THURXE_CWUSRM;

CREATE TABLE OEHR.THURXE_CWUSRM (
                                    ENO VARCHAR2(32),
                                    DEL_YN VARCHAR2(1),
                                    FST_ENR_DTM DATE,
                                    FST_ENR_USID VARCHAR2(14),
                                    GUID VARCHAR2(38),
                                    GUID_PRG_SNO NUMBER(4,0),
                                    LST_CHG_DTM DATE,
                                    LST_CHG_USID VARCHAR2(14),
                                    WEBA_PRO_NM VARCHAR2(100),
                                    WEBA_USR_HDLN_IMG BLOB,
                                    CONSTRAINT SYS_C0011196 CHECK ("ENO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011197 CHECK ("DEL_YN" IS NOT NULL),
                                    CONSTRAINT SYS_C0011198 CHECK ("FST_ENR_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011199 CHECK ("GUID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011200 CHECK ("GUID_PRG_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011201 CHECK ("LST_CHG_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011202 CHECK ("WEBA_PRO_NM" IS NOT NULL),
                                    CONSTRAINT SYS_C0011203 CHECK ("WEBA_USR_HDLN_IMG" IS NOT NULL),
                                    CONSTRAINT SYS_C0011204 PRIMARY KEY (ENO)
);



-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL

-- Drop table

-- DROP TABLE OEHR.THURXE_CWCRDM;

CREATE TABLE OEHR.THURXE_CWCRDM (
                                    WEBA_SNO NUMBER(10,0) DEFAULT "OEHR"."SQ_THURXE_CWCRDM_1".nextval,
                                    DEL_YN VARCHAR2(1),
                                    FST_ENR_DTM DATE,
                                    FST_ENR_USID VARCHAR2(14),
                                    GUID VARCHAR2(38),
                                    GUID_PRG_SNO NUMBER(4,0),
                                    LST_CHG_DTM DATE,
                                    LST_CHG_USID VARCHAR2(14),
                                    WEBA_CER_GUID_IMG BLOB,
                                    WEBA_CER_CNT NUMBER(10,0),
                                    WEBA_CFA_IMG BLOB,
                                    WEBA_OPNK_IMG BLOB,
                                    ENO VARCHAR2(32),
                                    CONSTRAINT SYS_C0011185 CHECK ("WEBA_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011186 CHECK ("DEL_YN" IS NOT NULL),
                                    CONSTRAINT SYS_C0011187 CHECK ("FST_ENR_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011188 CHECK ("GUID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011189 CHECK ("GUID_PRG_SNO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011190 CHECK ("LST_CHG_USID" IS NOT NULL),
                                    CONSTRAINT SYS_C0011191 CHECK ("WEBA_CER_CNT" IS NOT NULL),
                                    CONSTRAINT SYS_C0011192 CHECK ("WEBA_CFA_IMG" IS NOT NULL),
                                    CONSTRAINT SYS_C0011193 CHECK ("WEBA_OPNK_IMG" IS NOT NULL),
                                    CONSTRAINT SYS_C0011194 CHECK ("ENO" IS NOT NULL),
                                    CONSTRAINT SYS_C0011195 PRIMARY KEY (WEBA_SNO),
                                    CONSTRAINT FKSB9APKW2WGHV1LSFUYCXX2MBD FOREIGN KEY (ENO) REFERENCES OEHR.THURXE_CWUSRM(ENO)
);

CREATE TABLE OEHR.THURXE_SESSION (
                                     PRIMARY_ID CHAR(36) NOT NULL,
                                     SESSION_ID CHAR(36) NOT NULL,
                                     CREATION_TIME NUMBER NOT NULL,
                                     LAST_ACCESS_TIME NUMBER NOT NULL,
                                     MAX_INACTIVE_INTERVAL INT NOT NULL,
                                     EXPIRY_TIME NUMBER NOT NULL,
                                     PRINCIPAL_NAME VARCHAR2(100),
                                     CONSTRAINT THURXE_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX OEHR.THURXE_SESSION_IX1 ON OEHR.THURXE_SESSION (SESSION_ID);
CREATE INDEX OEHR.THURXE_SESSION_IX2 ON OEHR.THURXE_SESSION (EXPIRY_TIME);
CREATE INDEX OEHR.THURXE_SESSION_IX3 ON OEHR.THURXE_SESSION (PRINCIPAL_NAME);

COMMENT ON TABLE OEHR.THURXE_SESSION IS '인사_외부근태 세션정보테이블';
COMMENT ON COLUMN OEHR.THURXE_SESSION.PRIMARY_ID IS '기본 ID';
COMMENT ON COLUMN OEHR.THURXE_SESSION.SESSION_ID IS '세션 ID';
COMMENT ON COLUMN OEHR.THURXE_SESSION.CREATION_TIME IS '세션 생성 시간';
COMMENT ON COLUMN OEHR.THURXE_SESSION.LAST_ACCESS_TIME IS '마지막 접근 시간';
COMMENT ON COLUMN OEHR.THURXE_SESSION.MAX_INACTIVE_INTERVAL IS '최대 비활성화 간격';
COMMENT ON COLUMN OEHR.THURXE_SESSION.EXPIRY_TIME IS '세션 만료 시간';
COMMENT ON COLUMN OEHR.THURXE_SESSION.PRINCIPAL_NAME IS '주체 이름';

CREATE TABLE OEHR.THURXE_SESSION_ATTRIBUTES (
                                                SESSION_PRIMARY_ID CHAR(36) NOT NULL,
                                                ATTRIBUTE_NAME VARCHAR2(200) NOT NULL,
                                                ATTRIBUTE_BYTES BLOB NOT NULL,
                                                CONSTRAINT THURXE_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
                                                CONSTRAINT THURXE_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES OEHR.THURXE_SESSION(PRIMARY_ID) ON DELETE CASCADE
);

COMMENT ON TABLE OEHR.THURXE_SESSION_ATTRIBUTES IS '인사_외부근태 세션속성테이블';
COMMENT ON COLUMN OEHR.THURXE_SESSION_ATTRIBUTES.SESSION_PRIMARY_ID IS '세션 기본 ID';
COMMENT ON COLUMN OEHR.THURXE_SESSION_ATTRIBUTES.ATTRIBUTE_NAME IS '속성 이름';
COMMENT ON COLUMN OEHR.THURXE_SESSION_ATTRIBUTES.ATTRIBUTE_BYTES IS '속성 데이터';



--comment 모음

COMMENT ON TABLE OEHR.THURXE_CATHLI IS '인사_외부근태 공통자격등급기본';
COMMENT ON COLUMN OEHR.THURXE_CATHLI.ATH_ID IS '권한ID';
COMMENT ON COLUMN OEHR.THURXE_CATHLI.DEL_YN IS '삭제여부';
COMMENT ON COLUMN OEHR.THURXE_CATHLI.FST_ENR_DTM IS '생성일시';
COMMENT ON COLUMN OEHR.THURXE_CATHLI.FST_ENR_USID IS '생성사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CATHLI.GUID IS 'GUID';
COMMENT ON COLUMN OEHR.THURXE_CATHLI.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN OEHR.THURXE_CATHLI.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OEHR.THURXE_CATHLI.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CATHLI.QLF_GR_MAT IS '자격등급사항(내용)';
COMMENT ON COLUMN OEHR.THURXE_CATHLI.QLF_GR_NM IS '자격등급명';
COMMENT ON COLUMN OEHR.THURXE_CATHLI.USE_YN IS '사용여부';

COMMENT ON TABLE OEHR.THURXE_CBRDFM IS '인사_외부근태 공지사항게시판파일기본';
COMMENT ON COLUMN OEHR.THURXE_CBRDFM.BLB_APG_FL_SNO IS '게시판첨부파일일련번호';
COMMENT ON COLUMN OEHR.THURXE_CBRDFM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN OEHR.THURXE_CBRDFM.FST_ENR_DTM IS '생성일시';
COMMENT ON COLUMN OEHR.THURXE_CBRDFM.FST_ENR_USID IS '생성사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CBRDFM.GUID IS 'GUID';
COMMENT ON COLUMN OEHR.THURXE_CBRDFM.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN OEHR.THURXE_CBRDFM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OEHR.THURXE_CBRDFM.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CBRDFM.FL_KPN_PTH IS '파일저장경로';
COMMENT ON COLUMN OEHR.THURXE_CBRDFM.ORC_FL_NM IS '원본파일명';
COMMENT ON COLUMN OEHR.THURXE_CBRDFM.SVR_FL_NM IS '서버파일명';
COMMENT ON COLUMN OEHR.THURXE_CBRDFM.BLB_SNO IS '게시판일련번호';

COMMENT ON TABLE OEHR.THURXE_CBRDIM IS '인사_외부근태 공지사항게시판이미지기본';
COMMENT ON COLUMN OEHR.THURXE_CBRDIM.BLB_IMG_SNO IS '게시판이미지일련번호';
COMMENT ON COLUMN OEHR.THURXE_CBRDIM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN OEHR.THURXE_CBRDIM.FST_ENR_DTM IS '생성일시';
COMMENT ON COLUMN OEHR.THURXE_CBRDIM.FST_ENR_USID IS '생성사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CBRDIM.GUID IS 'GUID';
COMMENT ON COLUMN OEHR.THURXE_CBRDIM.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN OEHR.THURXE_CBRDIM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OEHR.THURXE_CBRDIM.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CBRDIM.ORC_FL_NM IS '원본파일명';
COMMENT ON COLUMN OEHR.THURXE_CBRDIM.SVR_FL_NM IS '서버파일명';
COMMENT ON COLUMN OEHR.THURXE_CBRDIM.BLB_SNO IS '게시판일련번호';

COMMENT ON TABLE OEHR.THURXE_CBRDMM IS '인사_외부근태 공지사항게시판메인기본';
COMMENT ON COLUMN OEHR.THURXE_CBRDMM.BLB_SNO IS '게시판일련번호';
COMMENT ON COLUMN OEHR.THURXE_CBRDMM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN OEHR.THURXE_CBRDMM.FST_ENR_DTM IS '생성일시';
COMMENT ON COLUMN OEHR.THURXE_CBRDMM.FST_ENR_USID IS '생성사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CBRDMM.GUID IS 'GUID';
COMMENT ON COLUMN OEHR.THURXE_CBRDMM.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN OEHR.THURXE_CBRDMM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OEHR.THURXE_CBRDMM.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CBRDMM.BLB_CONE IS '게시판내용';
COMMENT ON COLUMN OEHR.THURXE_CBRDMM.BLB_NM IS '게시판명';
COMMENT ON COLUMN OEHR.THURXE_CBRDMM.CTG_NM IS '카테고리명';
COMMENT ON COLUMN OEHR.THURXE_CBRDMM.DUPR_ENO IS '작성자사원번호';
COMMENT ON COLUMN OEHR.THURXE_CBRDMM.FL_APG_YN IS '파일첨부여부';
COMMENT ON COLUMN OEHR.THURXE_CBRDMM.NAC_INQ_NBR IS '게시물조회수';

COMMENT ON TABLE OEHR.THURXE_CCDHTA IS '인사_외부근태 HTML관계';
COMMENT ON COLUMN OEHR.THURXE_CCDHTA.DEL_YN IS '삭제여부';
COMMENT ON COLUMN OEHR.THURXE_CCDHTA.FST_ENR_DTM IS '생성일시';
COMMENT ON COLUMN OEHR.THURXE_CCDHTA.FST_ENR_USID IS '생성사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CCDHTA.GUID IS 'GUID';
COMMENT ON COLUMN OEHR.THURXE_CCDHTA.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN OEHR.THURXE_CCDHTA.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OEHR.THURXE_CCDHTA.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CCDHTA.SRE_VCB_CDVA_ID IS '화면용어코드값ID';
COMMENT ON COLUMN OEHR.THURXE_CCDHTA.HTML_FL_PTH IS 'HTML경로명';

COMMENT ON TABLE OEHR.THURXE_CHTMLM IS '인사_외부근태 HTML화면기본';
COMMENT ON COLUMN OEHR.THURXE_CHTMLM.HTML_FL_PTH IS 'HTML파일경로';
COMMENT ON COLUMN OEHR.THURXE_CHTMLM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN OEHR.THURXE_CHTMLM.FST_ENR_DTM IS '생성일시';
COMMENT ON COLUMN OEHR.THURXE_CHTMLM.FST_ENR_USID IS '생성사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CHTMLM.GUID IS 'GUID';
COMMENT ON COLUMN OEHR.THURXE_CHTMLM.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN OEHR.THURXE_CHTMLM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OEHR.THURXE_CHTMLM.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CHTMLM.HTML_FL_NM IS 'HTML파일명';

COMMENT ON TABLE OEHR.THURXE_CCODEM IS '인사_외부근태 언어기본';
COMMENT ON COLUMN OEHR.THURXE_CCODEM.SRE_VCB_CDVA_ID IS '화면용어코드값ID';
COMMENT ON COLUMN OEHR.THURXE_CCODEM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN OEHR.THURXE_CCODEM.FST_ENR_DTM IS '생성일시';
COMMENT ON COLUMN OEHR.THURXE_CCODEM.FST_ENR_USID IS '생성사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CCODEM.GUID IS 'GUID';
COMMENT ON COLUMN OEHR.THURXE_CCODEM.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN OEHR.THURXE_CCODEM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OEHR.THURXE_CCODEM.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CCODEM.SRE_VCB_KD_NM IS '화면용어종류명';
COMMENT ON COLUMN OEHR.THURXE_CCODEM.SRE_VCB_NM IS '화면용어명';

COMMENT ON TABLE OEHR.THURXE_CLOGNL IS '인사_외부근태 로그인로그';
COMMENT ON COLUMN OEHR.THURXE_CLOGNL.LGN_LOG_SNO IS '로그인로그일련번호';
COMMENT ON COLUMN OEHR.THURXE_CLOGNL.DEL_YN IS '삭제여부';
COMMENT ON COLUMN OEHR.THURXE_CLOGNL.FST_ENR_DTM IS '생성일시';
COMMENT ON COLUMN OEHR.THURXE_CLOGNL.FST_ENR_USID IS '생성사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CLOGNL.GUID IS 'GUID';
COMMENT ON COLUMN OEHR.THURXE_CLOGNL.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN OEHR.THURXE_CLOGNL.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OEHR.THURXE_CLOGNL.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CLOGNL.CER_KD_NM IS '로그인종류명';
COMMENT ON COLUMN OEHR.THURXE_CLOGNL.ENO IS '사원번호';
COMMENT ON COLUMN OEHR.THURXE_CLOGNL.LGN_SCS_YN IS '로그인성공여부';

COMMENT ON TABLE OEHR.THURXE_CORGLI IS '인사_외부근태 공통조직기본';
COMMENT ON COLUMN OEHR.THURXE_CORGLI.PRLM_OGZ_C_CONE IS '인사조직코드내용';
COMMENT ON COLUMN OEHR.THURXE_CORGLI.DEL_YN IS '삭제여부';
COMMENT ON COLUMN OEHR.THURXE_CORGLI.FST_ENR_DTM IS '생성일시';
COMMENT ON COLUMN OEHR.THURXE_CORGLI.FST_ENR_USID IS '생성사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CORGLI.GUID IS 'GUID';
COMMENT ON COLUMN OEHR.THURXE_CORGLI.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN OEHR.THURXE_CORGLI.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OEHR.THURXE_CORGLI.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CORGLI.BBR_NM IS '부점명';
COMMENT ON COLUMN OEHR.THURXE_CORGLI.BBR_WREN_NM IS '부점영문명';
COMMENT ON COLUMN OEHR.THURXE_CORGLI.ITM_SQN_SNO IS '항목순서일련번호';
COMMENT ON COLUMN OEHR.THURXE_CORGLI.PRLM_HRK_OGZ_C_CONE IS '인사상위조직코드내용';
COMMENT ON COLUMN OEHR.THURXE_CORGLI.USE_YN IS '사용여부';


COMMENT ON TABLE OEHR.THURXE_COTPIM IS '인사_외부근태 OTP발급이력기본';
COMMENT ON COLUMN OEHR.THURXE_COTPIM.OTP_ISN_SNO IS 'OTP발급일련번호';
COMMENT ON COLUMN OEHR.THURXE_COTPIM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN OEHR.THURXE_COTPIM.FST_ENR_DTM IS '생성일시';
COMMENT ON COLUMN OEHR.THURXE_COTPIM.FST_ENR_USID IS '생성사용자ID';
COMMENT ON COLUMN OEHR.THURXE_COTPIM.GUID IS 'GUID';
COMMENT ON COLUMN OEHR.THURXE_COTPIM.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN OEHR.THURXE_COTPIM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OEHR.THURXE_COTPIM.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN OEHR.THURXE_COTPIM.CER_KD_NM IS '인증종류명';
COMMENT ON COLUMN OEHR.THURXE_COTPIM.ENO IS '사원번호';
COMMENT ON COLUMN OEHR.THURXE_COTPIM.OTP_SMS_CER_NO IS 'OTPSMS인증번호';

COMMENT ON TABLE OEHR.THURXE_CROLEM IS '인사_외부근태 역할메인기본';
COMMENT ON COLUMN OEHR.THURXE_CROLEM.ENO IS '사원번호';
COMMENT ON COLUMN OEHR.THURXE_CROLEM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN OEHR.THURXE_CROLEM.FST_ENR_DTM IS '생성일시';
COMMENT ON COLUMN OEHR.THURXE_CROLEM.FST_ENR_USID IS '생성사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CROLEM.GUID IS 'GUID';
COMMENT ON COLUMN OEHR.THURXE_CROLEM.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN OEHR.THURXE_CROLEM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OEHR.THURXE_CROLEM.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CROLEM.ATH_ID IS '권한ID';

COMMENT ON TABLE OEHR.THURXE_CUSATI IS '인사_외부근태 공통사용자자격등급기본';
COMMENT ON COLUMN OEHR.THURXE_CUSATI.ENO IS '사원번호';
COMMENT ON COLUMN OEHR.THURXE_CUSATI.ATH_ID IS '권한ID';
COMMENT ON COLUMN OEHR.THURXE_CUSATI.DEL_YN IS '삭제여부';
COMMENT ON COLUMN OEHR.THURXE_CUSATI.FST_ENR_DTM IS '생성일시';
COMMENT ON COLUMN OEHR.THURXE_CUSATI.FST_ENR_USID IS '생성사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CUSATI.GUID IS 'GUID';
COMMENT ON COLUMN OEHR.THURXE_CUSATI.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN OEHR.THURXE_CUSATI.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OEHR.THURXE_CUSATI.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CUSATI.USE_YN IS '사용여부';

COMMENT ON TABLE OEHR.THURXE_CUSRLI IS '인사_외부근태 공통사용자기본';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.ENO IS '사원번호';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.DEL_YN IS '삭제여부';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.FST_ENR_DTM IS '생성일시';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.FST_ENR_USID IS '생성사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.GUID IS 'GUID';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.BBR_C IS '부점코드';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.CADR_TPN IS '연락처전화번호';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.DTC_BBR_C IS '파견부점코드';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.DTS_DTL_CONE IS '직무상세내용';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.ETR_MIL_ADDR_NM IS '전자우편주소명';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.INLE_NO IS '내선번호';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.PT_C IS '직위코드';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.PT_C_NM IS '직위코드명';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.TEM_C IS '팀코드';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.TEM_NM IS '팀명';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.USE_YN IS '사용여부';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.USR_NM IS '직원명';
COMMENT ON COLUMN OEHR.THURXE_CUSRLI.USR_WREN_NM IS '사용자영문명';


COMMENT ON TABLE OEHR.THURXE_CVIEWL IS '인사_외부근태 페이지뷰로그';
COMMENT ON COLUMN OEHR.THURXE_CVIEWL.PAG_LOG_SNO IS '페이지로그일련번호';
COMMENT ON COLUMN OEHR.THURXE_CVIEWL.DEL_YN IS '삭제여부';
COMMENT ON COLUMN OEHR.THURXE_CVIEWL.FST_ENR_DTM IS '생성일시';
COMMENT ON COLUMN OEHR.THURXE_CVIEWL.FST_ENR_USID IS '생성사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CVIEWL.GUID IS 'GUID';
COMMENT ON COLUMN OEHR.THURXE_CVIEWL.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN OEHR.THURXE_CVIEWL.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OEHR.THURXE_CVIEWL.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CVIEWL.CLI_IP_ADDR IS '클라이언트IP주소';
COMMENT ON COLUMN OEHR.THURXE_CVIEWL.CTRL_NM IS '컨트롤러명';
COMMENT ON COLUMN OEHR.THURXE_CVIEWL.MTH_NM IS '메소드명';
COMMENT ON COLUMN OEHR.THURXE_CVIEWL.REQ_URL_ADDR IS '요청URL주소';
COMMENT ON COLUMN OEHR.THURXE_CVIEWL.USR_CNC_ENV_CONE IS '사용자접속환경내용';

COMMENT ON TABLE OEHR.THURXE_CWCRDM IS '인사_외부근태 Webauthn자격증명기본';
COMMENT ON COLUMN OEHR.THURXE_CWCRDM.WEBA_SNO IS 'Webauthn 일련번호';
COMMENT ON COLUMN OEHR.THURXE_CWCRDM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN OEHR.THURXE_CWCRDM.FST_ENR_DTM IS '생성일시';
COMMENT ON COLUMN OEHR.THURXE_CWCRDM.FST_ENR_USID IS '생성사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CWCRDM.GUID IS 'GUID';
COMMENT ON COLUMN OEHR.THURXE_CWCRDM.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN OEHR.THURXE_CWCRDM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OEHR.THURXE_CWCRDM.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CWCRDM.WEBA_CER_GUID_IMG IS 'Webauthn인증GUID이미지';
COMMENT ON COLUMN OEHR.THURXE_CWCRDM.WEBA_CER_CNT IS 'Webauthn인증건수';
COMMENT ON COLUMN OEHR.THURXE_CWCRDM.WEBA_CFA_IMG IS 'Webauthn인증서이미지';
COMMENT ON COLUMN OEHR.THURXE_CWCRDM.WEBA_OPNK_IMG IS 'Webauthn공개키이미지';
COMMENT ON COLUMN OEHR.THURXE_CWCRDM.ENO IS '직원번호';

COMMENT ON TABLE OEHR.THURXE_CWUSRM IS '인사_외부근태 Webauthn사용자기본';
COMMENT ON COLUMN OEHR.THURXE_CWUSRM.ENO IS '직원번호';
COMMENT ON COLUMN OEHR.THURXE_CWUSRM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN OEHR.THURXE_CWUSRM.FST_ENR_DTM IS '생성일시';
COMMENT ON COLUMN OEHR.THURXE_CWUSRM.FST_ENR_USID IS '생성사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CWUSRM.GUID IS 'GUID';
COMMENT ON COLUMN OEHR.THURXE_CWUSRM.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN OEHR.THURXE_CWUSRM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN OEHR.THURXE_CWUSRM.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN OEHR.THURXE_CWUSRM.WEBA_PRO_NM IS 'Webauthn 출력명';
COMMENT ON COLUMN OEHR.THURXE_CWUSRM.WEBA_USR_HDLN_IMG IS 'Webauthn 사용자 Handle';

COMMENT ON TABLE OEHR.THURXE_SESSION IS '인사_외부근태 세션정보테이블';
COMMENT ON COLUMN OEHR.THURXE_SESSION.PRIMARY_ID IS '기본 ID';
COMMENT ON COLUMN OEHR.THURXE_SESSION.SESSION_ID IS '세션 ID';
COMMENT ON COLUMN OEHR.THURXE_SESSION.CREATION_TIME IS '세션 생성 시간';
COMMENT ON COLUMN OEHR.THURXE_SESSION.LAST_ACCESS_TIME IS '마지막 접근 시간';
COMMENT ON COLUMN OEHR.THURXE_SESSION.MAX_INACTIVE_INTERVAL IS '최대 비활성화 간격';
COMMENT ON COLUMN OEHR.THURXE_SESSION.EXPIRY_TIME IS '세션 만료 시간';
COMMENT ON COLUMN OEHR.THURXE_SESSION.PRINCIPAL_NAME IS '주체 이름';

COMMENT ON TABLE OEHR.THURXE_SESSION_ATTRIBUTES IS '인사_외부근태 세션속성테이블';
COMMENT ON COLUMN OEHR.THURXE_SESSION_ATTRIBUTES.SESSION_PRIMARY_ID IS '세션 기본 ID';
COMMENT ON COLUMN OEHR.THURXE_SESSION_ATTRIBUTES.ATTRIBUTE_NAME IS '속성 이름';
COMMENT ON COLUMN OEHR.THURXE_SESSION_ATTRIBUTES.ATTRIBUTE_BYTES IS '속성 데이터';